config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  resource :sign_up
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "products#index"
  resources :products do
    resources :subscribers, only: [ :create ]
  end

  namespace :settings do
    resource :email, only: [ :show, :update ]
    resource :password, only: [ :show, :update ]
    resource :profile, only: [ :show, :update ]
    resource :user, only: [ :show, :destroy ]

    root to: redirect("/settings/profile")
  end

  namespace :email do
    resources :confirmations, param: :token, only: [ :show ]
  end

  # Admins Only
  namespace :store do
    resources :products
    resources :users
    root to: redirect("/store/products")
  end


  get "unsubscribe/:token", to: "unsubscribes#show", as: :unsubscribe
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Store" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">


    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/nav" %>
    <%= render "shared/flash" %>
    <main>
      <%= content_for?(:content) ? yield(:content) : yield %>
    </main>
    <%= render "shared/footer" %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/settings.html.erb
<%= content_for :content do %>
  <div class="container mt-4">
    <div class="row">
      <div class="col-lg-3">
        <div class="card mb-4">
          <div class="card-header fw-bold">
            <%= t(".account_settings") %>
          </div>
          <ul class="list-group list-group-flush">
            <%= link_to t(".profile"), settings_profile_path, class: "list-group-item list-group-item-action #{is_active?(settings_profile_path)}" %>
            <%= link_to t(".email"), settings_email_path, class: "list-group-item list-group-item-action #{is_active?(settings_email_path)}" %>
            <%= link_to t(".password"), settings_password_path, class: "list-group-item list-group-item-action #{is_active?(settings_password_path)}" %>
            <%= link_to t(".account"), settings_user_path, class: "list-group-item list-group-item-action #{is_active?(settings_user_path)}" %>
          </ul>
        </div>

        <% if current_user.admin? %>
          <div class="card">
            <div class="card-header fw-bold">
              <%= t(".store_settings") %>
            </div>
            <ul class="list-group list-group-flush">
              <%= link_to t(".users"), store_users_path, class: "list-group-item list-group-item-action #{is_active?(store_users_path)}" %>
              <%= link_to t(".products"), store_products_path, class: "list-group-item list-group-item-action #{is_active?(store_products_path)}" %>
            </ul>
          </div>
        <% end %>
      </div>
      <div class="col-lg-9">
        <div class="card">
          <div class="card-body">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

<%= render template: "layouts/application" %>